# Generated by Django 5.0.6 on 2024-06-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento_id', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tema_Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tema', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=5000)),
                ('fecha_inico', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.BooleanField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='proyectos')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.persona')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.tema_proyecto')),
            ],
        ),
    ]
